### ISSUE TITLE
Erroneous terms in the corpus

### ISSUE THREAD

**Issue by adamlhayes** [ryscott5/eparTextTools#19] opened 2017-06-28 19:13 UTC
Reading pdfs into a corpus can produce a lot of terms with "â" (e.g., "theâ") at the beginning or end of the word as well as erroneous terms like: "â\u0080\u0093".

Consider including an additional function within doc_clean_process() to get rid of select special characters, something like the following:
removeSpecialChars <- content_transformer(function(x) gsub("[^a-zA-Z&-]"," ",x))

**Comment by Synaps3** [comment] 2017-07-15 02:57
We should merge this bug with bug #6 as they are both about the same thing.

Graham

**Comment by Synaps3** [comment] 2017-08-28 17:45
Closing, duplicate of #6

**Closed as completed by Synaps3** 2017-08-28 17:45 UTC
Labels: duplicate
